#!/bin/bash
set -e
PORT=$RANDOM
PORT=$((PORT + 1000))

BS=$1
LR=$2
NAME=bs${BS}-lr$LR
if [ -z "$3" ]; then
    CROSSING="--cross_layer=12 --coalesce_topk=concat --topk_coalesced=False"
else
    if [ "$3" == "none" ]; then
        CROSSING=""
    elif [ "$3" == "btopk" ]; then
        CROSSING="--activation=batchtopk"
    elif [ "$3" == "btopk-tied" ]; then
        CROSSING="--activation=batchtopk --cross_layer=12 --coalesce_topk=concat --topk_coalesced=False"
    elif [ "$3" == "tied" ]; then
        CROSSING="--cross_layer=12 --coalesce_topk=concat --topk_coalesced=False"
    elif [ "$3" == "cross" ]; then
        # CROSSING="--cross_layer=12 --coalesce_topk=per-layer --topk_coalesced=False"
        # CROSSING="--cross_layer=12 --divide_cross_layer=True --coalesce_topk=per-layer --topk_coalesced=False"
        CROSSING="--cross_layer=12 --divide_cross_layer=True"
        # CROSSING="--cross_layer=12"
    else
        echo "Invalid option: $3"
        exit 1
    fi
    NAME=${NAME}-$3
fi
if [ -z "$4" ]; then
    EF=128
else
    EF=$4
fi
NAME=${NAME}-ef$EF
if [ -z "$5" ]; then
    K=16
else
    K=$5
fi
NAME=${NAME}-k$K

if [ -z "$OPTIMIZER" ]; then
    OPTIMIZER="adam"
else
    NAME=${NAME}-${OPTIMIZER}
fi

SAVE_ARGS="--save_every 100000000000"
if ! [ -z "$DO_SAVE" ]; then
    if [ "$DO_SAVE" == "1" ]; then
        SAVE_ARGS="--save_every 2000"
    else
        SAVE_ARGS="--save_every $DO_SAVE"
    fi
fi

N_DEVICES=4
# N_DEVICES=1
# WANDB_ENTITY=eleutherai uv run python -m sparsify \
WANDB_ENTITY=eleutherai uv run torchrun --master_port $PORT --nproc_per_node gpu -m sparsify \
openai-community/gpt2 --ctx_len 128 --filter_bos=True \
--transcode=True --skip_connection=True \
--batch_size=$BS --expansion_factor=$EF --k=$K --tp=$N_DEVICES \
--hookpoints h.0.mlp h.1.mlp h.2.mlp h.3.mlp h.4.mlp h.5.mlp h.6.mlp h.7.mlp h.8.mlp h.9.mlp h.10.mlp h.11.mlp \
--run_name gpt2-sweep/$NAME \
$CROSSING \
--post_encoder_scale=True --normalize_io=True \
$SAVE_ARGS --lr $LR \
--optimizer $OPTIMIZER --lr_warmup_steps 50 \
# --resume
# --finetune /mnt/ssd-1/nev/e2e/checkpoints/gpt2-sweep/bs8-lr2e-4-none-ef128-k16/
